-- 사용자 테이블 생성
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) NOT NULL,
  email VARCHAR2(100) NOT NULL,
  password VARCHAR2(100) NOT NULL
);

-- 카테고리 테이블 생성
CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(50) NOT NULL
);

-- 게시물 테이블 생성
CREATE TABLE posts (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(100) NOT NULL,
  content CLOB NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id NUMBER NOT NULL,
  category_id NUMBER NOT NULL,
  CONSTRAINT fk_user
    FOREIGN KEY (user_id) 
    REFERENCES users(id),
  CONSTRAINT fk_category
    FOREIGN KEY (category_id) 
    REFERENCES categories(id)
);


-- 태그 테이블 생성
CREATE TABLE tags (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
   name VARCHAR2(50)
);



-- 댓글 테이블 생성
CREATE TABLE comments (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
   content CLOB NOT NULL, 
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
   user_id NUMBER NOT NULL, 
   post_id NUMBER NOT NULL,
   CONSTRAINT fk_comment_user
    FOREIGN KEY (user_id) 
    REFERENCES users(id),
   CONSTRAINT fk_comment_post
    FOREIGN KEY (post_id) 
    REFERENCES posts(id)
);

-- 제주도의 관광지 정보 테이블 생성
CREATE TABLE places (
    id INT PRIMARY KEY,
    name VARCHAR2(100),
    description CLOB,
    location VARCHAR2(255)
);


-- 사용자(User) 테이블에 새로운 사용자 추가
INSERT INTO users (username, email, password)
VALUES ('apple', 'apple@example.com', 'password123');

INSERT INTO users (username, email, password)
VALUES ('orange', 'orange@example.com', 'password456');

INSERT INTO users (username, email, password)
VALUES ('grape', 'grape@example.com', 'password789');

INSERT INTO users (username, email, password)
VALUES ('strawberry', 'strawberry@example.com', 'password385');

INSERT INTO users (username, email, password)
VALUES ('kiwi', 'kiwi@example.com', 'password346');


-- 임의의 카테고리 추가
INSERT INTO categories (name)
VALUES ('제주여행');

INSERT INTO categories (name)
VALUES ('제주맛집');

INSERT INTO categories (name)
VALUES ('제주명소');

INSERT INTO categories (name)
VALUES ('제주숙소');

INSERT INTO categories (name)
VALUES ('제주레저');


-- 댓글 추가
INSERT INTO comments (content, user_id, post_id)
VALUES ('한라산 정상에서 바라본 제주도의 풍경은 정말 멋집니다!', 1, 1);
INSERT INTO comments (content, user_id, post_id)
VALUES ('성산일출봉에서 본 일출은 정말 감동적이었습니다.', 2, 2);
INSERT INTO comments (content, user_id, post_id)
VALUES ('천지연폭포의 물소리를 들으며 힐링하고 왔습니다.', 3, 3);
INSERT INTO comments (content, user_id, post_id)
VALUES ('우도의 바다 색깔은 정말 맑고 푸르네요.', 4, 4);
INSERT INTO comments (content, user_id, post_id)
VALUES ('비자림은 산책하기 정말 좋은 곳입니다.', 5, 5);


-- 임의의 게시물 추가
INSERT INTO posts (title, content, user_id, category_id)
VALUES ('첫 번째 게시물', '안녕하세요.', 1, 1);

INSERT INTO posts (title, content, user_id, category_id)
VALUES ('두 번째 게시물', '반갑습니다.', 2, 2);

INSERT INTO posts (title, content, user_id, category_id)
VALUES ('세 번째 게시물', '오늘 날씨가 좋네요.', 3, 1);

INSERT INTO posts (title, content, user_id, category_id)
VALUES ('네 번째 게시물', '여기는 한국입니다.', 4, 2);

INSERT INTO posts (title, content, user_id, category_id)
VALUES ('다섯 번째 게시물', '제 이름은 000입니다.', 5, 1);


-- 임의의 테그 테이블 추가
INSERT INTO tags (name)
VALUES ('제주도');
INSERT INTO tags (name)
VALUES ('한라산');
INSERT INTO tags (name)
VALUES ('성산일출봉');
INSERT INTO tags (name)
VALUES ('우도');
INSERT INTO tags (name)
VALUES ('해녀');



-- 지역 정보 추가
INSERT INTO places (id, name, description, location)
VALUES (1, '한라산', '한라산은 제주도의 중심에 위치한 화산으로, 한라산 국립공원의 주요한 명소입니다. 등반로가 잘 정비되어 있어 많은 등산객들이 찾습니다.', '제주시 한라산로 300');
INSERT INTO places (id, name, description, location)
VALUES (2, '성산일출봉', '성산일출봉은 제주도 동쪽에 위치한 화산으로, 일출이 아름답게 보이는 곳으로 유명합니다. 유네스코 세계자연유산에 등재되어 있습니다.', '서귀포시 성산읍 일출로 284-12');
INSERT INTO places (id, name, description, location)
VALUES (3, '천지연폭포', '천지연폭포는 제주도 서귀포시에 위치한 폭포로, 제주도의 아름다움을 대표하는 자연 명소 중 하나입니다.', '서귀포시 천지연로 132');
INSERT INTO places (id, name, description, location)
VALUES (4, '우도', '우도는 제주도 동쪽에 위치한 섬으로, 아름다운 해변과 독특한 지형으로 유명합니다. 바이크나 오토바이로 둘러보는 것이 인기 있습니다.', '제주시 우도면');
INSERT INTO places (id, name, description, location)
VALUES (5, '비자림', '비자림은 제주도의 중심부에 위치한 숲으로, 걷기 좋은 산책로와 다양한 식물 종을 볼 수 있습니다. 특히 여름에는 시원한 휴식처로 많은 사람들이 찾습니다.', '제주시 조천읍 비자림로 1');